import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import { JobPost } from '../../job-posts/entities/job-post.entity';

export default class JobPostSeeder implements Seeder {
  public async run(dataSource: DataSource): Promise<any> {
    const repository = dataSource.getRepository(JobPost);

    console.log('🌱 Seeding user...');
    await repository.insert([
      {
        title: '기장대게 할인마트 홀 서빙 대타 구함!',
        location: '부산광역시 기장군 민락동',
        pay: 90000,
        date: new Date('2025-07-12'),
        startTime: '14:00',
        endTime: '18:00',
        imageUrl: 'https://your-cdn.com/images/kijang-crab-mart.jpg',
        place: '기장대게할인마트',
        totalHours: 4,
        createdAt: new Date('2025-07-15T19:55:00'),
      },
      {
        title: '홍대 뷔페 식당 점심 서빙 알바 모집',
        location: '서울 마포구 홍익로 5길',
        pay: 75000,
        date: new Date('2025-07-14'),
        startTime: '12:00',
        endTime: '17:00',
        imageUrl: 'https://your-cdn.com/images/hongdae-buffet.jpg',
        place: '홍대푸드뷔페',
        totalHours: 5,
        createdAt: new Date('2025-07-12T04:03:00'),
      },
      {
        title: '이마트24 계산대 단기 알바',
        location: '서울 강남구 역삼동',
        pay: 60000,
        date: new Date('2025-07-15'),
        startTime: '14:00',
        endTime: '17:00',
        imageUrl: 'https://your-cdn.com/images/emart24.jpg',
        place: '이마트24 역삼점',
        totalHours: 3,
        createdAt: new Date('2025-07-17T04:47:00'),
      },
      {
        title: '카페 알바 급구 - 음료 서빙 및 정리',
        location: '서울 송파구 잠실동',
        pay: 50000,
        date: new Date('2025-07-15'),
        startTime: '20:00',
        endTime: '23:00',
        imageUrl: 'https://your-cdn.com/images/cafe-job.jpg',
        place: '카페 노블레스',
        totalHours: 3,
        createdAt: new Date('2025-07-16T10:31:00'),
      },
      {
        title: '편의점 야간 정리 및 계산',
        location: '인천 부평구 부평동',
        pay: 65000,
        date: new Date('2025-07-16'),
        startTime: '07:00',
        endTime: '12:00',
        imageUrl: 'https://your-cdn.com/images/convenience-night.jpg',
        place: 'GS25 부평중앙점',
        totalHours: 5,
        createdAt: new Date('2025-07-18T12:23:00'),
      },
      {
        title: '식당 주방보조 단기 아르바이트',
        location: '부산 해운대구 우동',
        pay: 80000,
        date: new Date('2025-07-17'),
        startTime: '16:00',
        endTime: '19:00',
        imageUrl: 'https://your-cdn.com/images/kitchen-helper.jpg',
        place: '해운대 국수집',
        totalHours: 3,
        createdAt: new Date('2025-07-17T02:06:00'),
      },
      {
        title: '행사 도우미 모집 (백화점 팝업존)',
        location: '서울 강남구 신사동',
        pay: 100000,
        date: new Date('2025-07-17'),
        startTime: '14:00',
        endTime: '17:00',
        imageUrl: 'https://your-cdn.com/images/event-helper.jpg',
        place: '현대백화점 신사점',
        totalHours: 3,
        createdAt: new Date('2025-07-14T22:30:00'),
      },
      {
        title: '서점 진열 보조 알바',
        location: '대구 중구 동성로',
        pay: 40000,
        date: new Date('2025-07-18'),
        startTime: '07:00',
        endTime: '12:00',
        imageUrl: 'https://your-cdn.com/images/bookstore-job.jpg',
        place: '동성로문고',
        totalHours: 5,
        createdAt: new Date('2025-07-18T07:02:00'),
      },
      {
        title: '마트 시식코너 단기 알바',
        location: '광주 서구 치평동',
        pay: 70000,
        date: new Date('2025-07-18'),
        startTime: '07:00',
        endTime: '10:00',
        imageUrl: 'https://your-cdn.com/images/sample-counter.jpg',
        place: '홈플러스 광주점',
        totalHours: 3,
        createdAt: new Date('2025-07-16T02:31:00'),
      },
      {
        title: '영화관 티켓/매점 스태프 알바',
        location: '서울 용산구 한강로동',
        pay: 60000,
        date: new Date('2025-07-18'),
        startTime: '20:00',
        endTime: '26:00',
        imageUrl: 'https://your-cdn.com/images/cinema-job.jpg',
        place: 'CGV 용산아이파크몰',
        totalHours: 6,
        createdAt: new Date('2025-07-13T16:47:00'),
      },
    ]);
  }
}
