import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import { JobPost } from '../../job-posts/entities/job-post.entity';

export default class JobPostSeeder implements Seeder {
  public async run(dataSource: DataSource): Promise<any> {
    const repository = dataSource.getRepository(JobPost);

    console.log('🌱 Seeding job post...');

    const jobPosts = [
      {
        title: '편의점 오후 알바',
        location: '인천 연수구 송도동',
        hourlyWage: 12800,
        startTime: '16:00',
        endTime: '22:00',
        totalHours: 6,
        pay: 76800,
        date: new Date('2025-09-03'),
        createdAt: new Date('2025-08-18T10:12:00'),
        place: 'GS25 송도국제점',
        imageUrl: null,
        content: '카운터랑 진열 위주예요. 처음이셔도 천천히 알려드려요!',
        userId: 1,
      },
      {
        title: '카페 주말 바리스타 보조',
        location: '서울 마포구 합정동',
        hourlyWage: 9200,
        startTime: '10:00',
        endTime: '16:00',
        totalHours: 6,
        pay: 55200,
        date: new Date('2025-09-07'),
        createdAt: new Date('2025-08-29T14:40:00'),
        place: '라떼포레스트 합정',
        imageUrl: null,
        content: '샷 추출/컵 세팅 같이해요. 밝게 인사만 잘해도 충분!',
        userId: 2,
      },
      {
        title: '행사 스태프(부스 안내)',
        location: '서울 강남구 대치동',
        hourlyWage: 15000,
        startTime: '12:00',
        endTime: '18:00',
        totalHours: 6,
        pay: 90000,
        date: new Date('2025-09-14'),
        createdAt: new Date('2025-09-01T09:05:00'),
        place: '코엑스 D홀',
        imageUrl: null,
        content: '부스 위치 안내하고 줄 정리해요. 활동적인 분이면 딱!',
        userId: 3,
      },
      {
        title: '서점 오후 진열 보조',
        location: '서울 종로구 관철동',
        hourlyWage: 8600,
        startTime: '13:00',
        endTime: '19:00',
        totalHours: 6,
        pay: 51600,
        date: new Date('2025-09-10'),
        createdAt: new Date('2025-08-20T16:22:00'),
        place: '문학당 서점 종각',
        imageUrl: null,
        content: '신간 정리하고 포장 도와주세요. 조용한 분위기예요 🙂',
        userId: 4,
      },
      {
        title: '버블티 매장 평일 저녁',
        location: '서울 서초구 서초동',
        hourlyWage: 9900,
        startTime: '17:00',
        endTime: '22:00',
        totalHours: 5,
        pay: 49500,
        date: new Date('2025-09-09'),
        createdAt: new Date('2025-08-25T12:10:00'),
        place: '타피오까라운지 서초',
        imageUrl: null,
        content: '펄 삶는 법부터 차근차근! 손 빠르신 분 환영합니다.',
        userId: 5,
      },
      {
        title: '영화관 팝콘 키친',
        location: '서울 송파구 가락동',
        hourlyWage: 8800,
        startTime: '15:00',
        endTime: '21:00',
        totalHours: 6,
        pay: 52800,
        date: new Date('2025-09-20'),
        createdAt: new Date('2025-09-02T18:30:00'),
        place: 'CINE7 가락',
        imageUrl: null,
        content: '팝콘·음료 준비하고 간단 청소해요. 함께 재밌게 일해요!',
        userId: 1,
      },
      {
        title: '베이커리 포장 알바',
        location: '경기 수원시 영통구 영통동',
        hourlyWage: 9400,
        startTime: '07:00',
        endTime: '11:00',
        totalHours: 4,
        pay: 37600,
        date: new Date('2025-09-05'),
        createdAt: new Date('2025-08-17T06:55:00'),
        place: '소금빵연구소 영통',
        imageUrl: null,
        content: '포장/라벨 위주라 어렵지 않아요. 아침형 환영!',
        userId: 2,
      },
      {
        title: '플리마켓 판매 도우미',
        location: '서울 성동구 성수동',
        hourlyWage: 10800,
        startTime: '11:00',
        endTime: '17:00',
        totalHours: 6,
        pay: 64800,
        date: new Date('2025-09-21'),
        createdAt: new Date('2025-08-31T11:00:00'),
        place: '성수 주말마켓',
        imageUrl: null,
        content: '부스 세팅하고 결제 도와요. 활기찬 분위기 좋아요!',
        userId: 3,
      },
      {
        title: '이사 짐 정리 보조',
        location: '서울 동작구 사당동',
        hourlyWage: 10200,
        startTime: '09:00',
        endTime: '15:00',
        totalHours: 6,
        pay: 61200,
        date: new Date('2025-09-12'),
        createdAt: new Date('2025-08-26T08:20:00'),
        place: '힘센이사 사당',
        imageUrl: null,
        content: '가벼운 박스 위주로 옮겨요. 천천히 해도 괜찮아요!',
        userId: 4,
      },
      {
        title: '전단지 배포(아파트 단지)',
        location: '서울 강서구 화곡동',
        hourlyWage: 9700,
        startTime: '13:00',
        endTime: '18:00',
        totalHours: 5,
        pay: 48500,
        date: new Date('2025-09-11'),
        createdAt: new Date('2025-08-24T13:10:00'),
        place: '에듀케어 학원',
        imageUrl: null,
        content: '동선 알려드려요. 이어폰 끼고 해도 OK!',
        userId: 5,
      },
      {
        title: '사진관 보정 어시스턴트',
        location: '서울 광진구 화양동',
        hourlyWage: 11000,
        startTime: '14:00',
        endTime: '19:00',
        totalHours: 5,
        pay: 55000,
        date: new Date('2025-09-18'),
        createdAt: new Date('2025-09-03T15:35:00'),
        place: '스튜디오 라이트업',
        imageUrl: null,
        content: '간단 후보정 배워가요. 친절히 차근차근 알려드려요!',
        userId: 1,
      },
      {
        title: '창고 피킹/패킹',
        location: '경기 부천시 원미구 상동',
        hourlyWage: 10000,
        startTime: '10:00',
        endTime: '16:00',
        totalHours: 6,
        pay: 60000,
        date: new Date('2025-09-16'),
        createdAt: new Date('2025-08-22T10:45:00'),
        place: '패스트로지스 상동',
        imageUrl: null,
        content: '스캔→포장 루틴이라 금방 익혀요. 쉬운 편이에요!',
        userId: 2,
      },
      {
        title: '치킨집 홀서빙',
        location: '서울 은평구 불광동',
        hourlyWage: 9500,
        startTime: '18:00',
        endTime: '23:00',
        totalHours: 5,
        pay: 47500,
        date: new Date('2025-09-19'),
        createdAt: new Date('2025-09-04T19:10:00'),
        place: '치킨행 복불광',
        imageUrl: null,
        content: '주문 받고 서빙해요. 바쁜 시간엔 모두 같이 도와요!',
        userId: 3,
      },
      {
        title: '학원 데스크 보조',
        location: '서울 노원구 상계동',
        hourlyWage: 9100,
        startTime: '16:00',
        endTime: '21:00',
        totalHours: 5,
        pay: 45500,
        date: new Date('2025-09-23'),
        createdAt: new Date('2025-08-30T09:50:00'),
        place: '상계러닝랩',
        imageUrl: null,
        content: '출석 체크·교재 정리해요. 응대 어렵지 않아요!',
        userId: 4,
      },
      {
        title: '서브웨이 샌드위치 제작',
        location: '서울 동대문구 장안동',
        hourlyWage: 8700,
        startTime: '11:00',
        endTime: '15:00',
        totalHours: 4,
        pay: 34800,
        date: new Date('2025-09-08'),
        createdAt: new Date('2025-08-19T12:03:00'),
        place: '서브웨이 장안점',
        imageUrl: null,
        content: '레시피만 따라오시면 금방 끝! 친절한 팀이에요.',
        userId: 5,
      },
      {
        title: '전시회 안내 도슨트 보조',
        location: '서울 용산구 이태원동',
        hourlyWage: 14200,
        startTime: '12:00',
        endTime: '18:00',
        totalHours: 6,
        pay: 85200,
        date: new Date('2025-10-05'),
        createdAt: new Date('2025-09-07T10:10:00'),
        place: '아트빌리지 전시장',
        imageUrl: null,
        content: '간단한 설명만 드려요. 스크립트 제공돼요!',
        userId: 1,
      },
      {
        title: '헬스장 데스크 주말',
        location: '서울 관악구 봉천동',
        hourlyWage: 9800,
        startTime: '09:00',
        endTime: '14:00',
        totalHours: 5,
        pay: 49000,
        date: new Date('2025-10-12'),
        createdAt: new Date('2025-09-09T08:40:00'),
        place: '피트랩 봉천',
        imageUrl: null,
        content: '회원 등록/수건 정리 정도예요. 어렵지 않아요!',
        userId: 2,
      },
      {
        title: '반려동물 카페 서포터',
        location: '서울 성북구 정릉동',
        hourlyWage: 10500,
        startTime: '12:00',
        endTime: '18:00',
        totalHours: 6,
        pay: 63000,
        date: new Date('2025-10-06'),
        createdAt: new Date('2025-08-28T17:25:00'),
        place: '퍼피스팟 정릉',
        imageUrl: null,
        content: '간식 준비하고 매장 정리해요. 동물 좋아하면 딱!',
        userId: 3,
      },
      {
        title: '빨래방 관리 보조',
        location: '서울 강북구 미아동',
        hourlyWage: 8900,
        startTime: '15:00',
        endTime: '20:00',
        totalHours: 5,
        pay: 44500,
        date: new Date('2025-10-03'),
        createdAt: new Date('2025-09-01T20:20:00'),
        place: '워시앤고 미아',
        imageUrl: null,
        content: '세제 보충·기기 확인만 해주시면 돼요. 쉬운 편!',
        userId: 4,
      },
      {
        title: '편의점 아침 물류 정리',
        location: '부산 해운대구 우동',
        hourlyWage: 8500,
        startTime: '07:00',
        endTime: '11:00',
        totalHours: 4,
        pay: 34000,
        date: new Date('2025-09-28'),
        createdAt: new Date('2025-08-27T07:05:00'),
        place: 'CU 해운대역점',
        imageUrl: null,
        content: '입고 물품 정리해요. 유통기한 체크만 기억해요!',
        userId: 5,
      },
      {
        title: '플라워샵 포장',
        location: '대전 유성구 봉명동',
        hourlyWage: 9300,
        startTime: '13:00',
        endTime: '18:00',
        totalHours: 5,
        pay: 46500,
        date: new Date('2025-10-10'),
        createdAt: new Date('2025-09-06T13:30:00'),
        place: '블룸가든 유성',
        imageUrl: null,
        content: '리본 묶는 법 알려드려요. 손재주 없어도 OK!',
        userId: 1,
      },
      {
        title: '축제 부스 운영(게임존)',
        location: '대구 수성구 범어동',
        hourlyWage: 12000,
        startTime: '11:00',
        endTime: '17:00',
        totalHours: 6,
        pay: 72000,
        date: new Date('2025-10-19'),
        createdAt: new Date('2025-09-12T10:00:00'),
        place: '범어가을축제',
        imageUrl: null,
        content: '게임 룰만 안내하면 돼요. 분위기 신나요 🎉',
        userId: 2,
      },
      {
        title: '키즈카페 안전요원',
        location: '경기 고양시 일산서구 주엽동',
        hourlyWage: 9400,
        startTime: '13:00',
        endTime: '19:00',
        totalHours: 6,
        pay: 56400,
        date: new Date('2025-10-13'),
        createdAt: new Date('2025-09-08T09:42:00'),
        place: '점핑키즈 주엽',
        imageUrl: null,
        content: '안전 라인만 봐주시면 돼요. 친절히 안내해요!',
        userId: 3,
      },
      {
        title: '푸드코트 서빙',
        location: '광주 서구 치평동',
        hourlyWage: 9000,
        startTime: '12:00',
        endTime: '18:00',
        totalHours: 6,
        pay: 54000,
        date: new Date('2025-10-02'),
        createdAt: new Date('2025-09-01T11:55:00'),
        place: '스타몰 푸드코트',
        imageUrl: null,
        content: '진동벨 전달하고 테이블 정리해요. 금방 익숙해져요!',
        userId: 4,
      },
      {
        title: 'PC방 카운터/정리',
        location: '인천 남동구 구월동',
        hourlyWage: 9800,
        startTime: '18:00',
        endTime: '23:00',
        totalHours: 5,
        pay: 49000,
        date: new Date('2025-09-30'),
        createdAt: new Date('2025-09-05T17:18:00'),
        place: '프로게이밍PC 구월',
        imageUrl: null,
        content: '자리 안내·간단 청소 위주예요. 야간 알바 처음도 환영!',
        userId: 5,
      },
      {
        title: '서점 북카페 저녁 타임',
        location: '서울 중구 을지로동',
        hourlyWage: 9100,
        startTime: '17:00',
        endTime: '22:00',
        totalHours: 5,
        pay: 45500,
        date: new Date('2025-10-08'),
        createdAt: new Date('2025-09-03T12:34:00'),
        place: '을지북라운지',
        imageUrl: null,
        content: '디저트 간단 준비하고 좌석 정리해요. 차분한 근무!',
        userId: 1,
      },
      {
        title: '샐러드 매장 런치',
        location: '서울 강남구 역삼동',
        hourlyWage: 9600,
        startTime: '11:00',
        endTime: '15:00',
        totalHours: 4,
        pay: 38400,
        date: new Date('2025-09-25'),
        createdAt: new Date('2025-08-23T10:02:00'),
        place: '그린볼 역삼',
        imageUrl: null,
        content: '토핑 세팅하고 포장해요. 점심 타임만 함께해요!',
        userId: 2,
      },
      {
        title: '전통시장 판매 지원',
        location: '서울 동대문구 제기동',
        hourlyWage: 8700,
        startTime: '10:00',
        endTime: '16:00',
        totalHours: 6,
        pay: 52200,
        date: new Date('2025-10-01'),
        createdAt: new Date('2025-09-02T08:48:00'),
        place: '제기시장 먹거리존',
        imageUrl: null,
        content: '시식 도와드리고 정리해요. 동네시장 감성 좋아요!',
        userId: 3,
      },
      {
        title: '카메라 렌탈샵 스태프',
        location: '서울 마포구 서교동',
        hourlyWage: 11100,
        startTime: '12:00',
        endTime: '19:00',
        totalHours: 7,
        pay: 77700,
        date: new Date('2025-10-17'),
        createdAt: new Date('2025-09-11T16:16:00'),
        place: '렌탈픽 서교',
        imageUrl: null,
        content: '렌즈 상태 체크만 잘해주시면 돼요. 매뉴얼 제공!',
        userId: 4,
      },
      {
        title: '도넛샵 포장/서빙',
        location: '서울 용산구 한남동',
        hourlyWage: 9200,
        startTime: '09:00',
        endTime: '13:00',
        totalHours: 4,
        pay: 36800,
        date: new Date('2025-09-27'),
        createdAt: new Date('2025-08-21T09:20:00'),
        place: '한남도넛스',
        imageUrl: null,
        content: '포장 위주라 금방 익혀요. 시식 도넛 살짝 있어요 🍩',
        userId: 5,
      },
      {
        title: '주차 안내 보조',
        location: '서울 서대문구 창천동',
        hourlyWage: 10000,
        startTime: '14:00',
        endTime: '20:00',
        totalHours: 6,
        pay: 60000,
        date: new Date('2025-10-09'),
        createdAt: new Date('2025-09-04T07:45:00'),
        place: '신촌몰 주차장',
        imageUrl: null,
        content: '차량 유도만 해주시면 됩니다. 무전기 사용 간단해요!',
        userId: 1,
      },
      {
        title: '서브컬처 페스티벌 안내',
        location: '서울 구로구 구로동',
        hourlyWage: 14500,
        startTime: '10:00',
        endTime: '17:00',
        totalHours: 7,
        pay: 101500,
        date: new Date('2025-10-26'),
        createdAt: new Date('2025-09-14T13:13:00'),
        place: '구로컨벤션',
        imageUrl: null,
        content: '티켓 스캔/줄 정리해요. 팬분들과 즐겁게 일해요!',
        userId: 2,
      },
      {
        title: '수제버거 매장 저녁',
        location: '서울 영등포구 당산동',
        hourlyWage: 9800,
        startTime: '17:00',
        endTime: '22:00',
        totalHours: 5,
        pay: 49000,
        date: new Date('2025-09-22'),
        createdAt: new Date('2025-09-06T18:18:00'),
        place: '브루클린버거 당산',
        imageUrl: null,
        content: '주문/포장 위주, 마감은 다 같이 빨리 끝내요!',
        userId: 3,
      },
      {
        title: '문구점 포장 보조',
        location: '서울 도봉구 창동',
        hourlyWage: 8800,
        startTime: '12:00',
        endTime: '17:00',
        totalHours: 5,
        pay: 44000,
        date: new Date('2025-09-26'),
        createdAt: new Date('2025-08-30T15:00:00'),
        place: '스마일문구 창동',
        imageUrl: null,
        content: '온라인 주문 포장하고 송장 붙이면 끝! 단순작업 좋아요.',
        userId: 4,
      },
      {
        title: '샌드아트 체험 부스',
        location: '인천 계양구 작전동',
        hourlyWage: 9700,
        startTime: '11:00',
        endTime: '17:00',
        totalHours: 6,
        pay: 58200,
        date: new Date('2025-10-20'),
        createdAt: new Date('2025-09-10T10:40:00'),
        place: '작전문화축제장',
        imageUrl: null,
        content: '체험 안내하고 정리만 같이해요. 아이들 좋아하면 굿!',
        userId: 5,
      },
      {
        title: '스터디카페 매니저 보조',
        location: '서울 금천구 가산동',
        hourlyWage: 9400,
        startTime: '18:00',
        endTime: '23:00',
        totalHours: 5,
        pay: 47000,
        date: new Date('2025-11-02'),
        createdAt: new Date('2025-09-20T19:22:00'),
        place: '포커스가산 스터디',
        imageUrl: null,
        content: '좌석 점검/소음 체크해요. 차분한 일 좋아하시면 딱!',
        userId: 1,
      },
      {
        title: '도시락 포장 라인',
        location: '서울 강동구 길동',
        hourlyWage: 8900,
        startTime: '09:00',
        endTime: '15:00',
        totalHours: 6,
        pay: 53400,
        date: new Date('2025-10-14'),
        createdAt: new Date('2025-09-07T05:50:00'),
        place: '헬로도시락 길동',
        imageUrl: null,
        content: '라벨 붙이고 포장만 해요. 위생모 지급합니다!',
        userId: 2,
      },
      {
        title: '마카롱 공방 포장',
        location: '서울 서대문구 홍은동',
        hourlyWage: 9500,
        startTime: '13:00',
        endTime: '18:00',
        totalHours: 5,
        pay: 47500,
        date: new Date('2025-09-29'),
        createdAt: new Date('2025-09-09T14:22:00'),
        place: '핑크마카롱 홍은',
        imageUrl: null,
        content: '상자 접고 스티커 붙이면 끝! 달콤한 근무예요 🍬',
        userId: 3,
      },
      {
        title: '세차장 서포트',
        location: '서울 중랑구 면목동',
        hourlyWage: 9300,
        startTime: '10:00',
        endTime: '16:00',
        totalHours: 6,
        pay: 55800,
        date: new Date('2025-10-04'),
        createdAt: new Date('2025-09-01T09:09:00'),
        place: '클린워시 면목',
        imageUrl: null,
        content: '물기 제거·매트 털기 정도예요. 금방 익숙해져요!',
        userId: 4,
      },
      {
        title: '와플샵 주말 오후',
        location: '서울 양천구 목동',
        hourlyWage: 9100,
        startTime: '14:00',
        endTime: '20:00',
        totalHours: 6,
        pay: 54600,
        date: new Date('2025-10-11'),
        createdAt: new Date('2025-09-13T16:44:00'),
        place: '크리스피와플 목동',
        imageUrl: null,
        content: '와플 굽기/토핑 같이해요. 달달한 냄새 가득!',
        userId: 5,
      },
    ];

    await repository.save(jobPosts);
  }
}
