import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import { JobPost } from '../../job-posts/entities/job-post.entity';

export default class JobPostSeeder implements Seeder {
  public async run(dataSource: DataSource): Promise<any> {
    const repository = dataSource.getRepository(JobPost);

    console.log('🌱 Seeding user...');

    await repository.insert([
      {
        title: '카페 서빙 아르바이트',
        location: '대전 서구 둔산동',
        pay: 78000,
        date: new Date('2025-07-22'),
        startTime: '10:00',
        endTime: '15:00',
        imageUrl: null,
        place: '카페 이디야',
        totalHours: 5,
        createdAt: new Date('2025-07-21T06:00:00'),
        content: '카페 서빙 아르바이트 업무입니다.',
      },
      {
        title: '편의점 야간 알바',
        location: '인천 연수구 송도동',
        pay: 166000,
        date: new Date('2025-07-19'),
        startTime: '16:00',
        endTime: '24:00',
        imageUrl: null,
        place: 'GS25 동네점',
        totalHours: 9,
        createdAt: new Date('2025-07-13T05:00:00'),
        content: '편의점 야간 알바 업무입니다.',
      },
      {
        title: '식당 설거지 도우미',
        location: '서울 강남구 역삼동',
        pay: 104000,
        date: new Date('2025-07-04'),
        startTime: '14:00',
        endTime: '24:00',
        imageUrl: null,
        place: '김밥천국 중앙점',
        totalHours: 10,
        createdAt: new Date('2025-07-01T12:00:00'),
        content: '식당 설거지 도우미 업무입니다.',
      },
      {
        title: '백화점 안내 도우미',
        location: '경기 성남시 분당구',
        pay: 61000,
        date: new Date('2025-07-24'),
        startTime: '15:00',
        endTime: '22:00',
        imageUrl: null,
        place: '현대백화점 무역점',
        totalHours: 7,
        createdAt: new Date('2025-07-23T13:00:00'),
        content: '백화점 안내 도우미 업무입니다.',
      },
      {
        title: '서점 진열 알바',
        location: '대전 서구 둔산동',
        pay: 126000,
        date: new Date('2025-07-04'),
        startTime: '08:00',
        endTime: '18:00',
        imageUrl: null,
        place: '동네서점책방',
        totalHours: 10,
        createdAt: new Date('2025-07-03T16:00:00'),
        content: '서점 진열 알바 업무입니다.',
      },
      {
        title: '마트 계산대 보조',
        location: '경기 성남시 분당구',
        pay: 121000,
        date: new Date('2025-07-07'),
        startTime: '16:00',
        endTime: '24:00',
        imageUrl: null,
        place: '이마트 성수점',
        totalHours: 8,
        createdAt: new Date('2025-07-05T21:00:00'),
        content: '마트 계산대 보조 업무입니다.',
      },
      {
        title: '레스토랑 홀 서빙',
        location: '전북 전주시 완산구',
        pay: 64000,
        date: new Date('2025-07-04'),
        startTime: '15:00',
        endTime: '19:00',
        imageUrl: null,
        place: '레스토랑 마르쉐',
        totalHours: 4,
        createdAt: new Date('2025-06-30T10:00:00'),
        content: '레스토랑 홀 서빙 업무입니다.',
      },
      {
        title: '영화관 입장 안내',
        location: '경기 성남시 분당구',
        pay: 62000,
        date: new Date('2025-07-27'),
        startTime: '12:00',
        endTime: '16:00',
        imageUrl: null,
        place: 'CGV 왕십리',
        totalHours: 4,
        createdAt: new Date('2025-07-21T05:00:00'),
        content: '영화관 입장 안내 업무입니다.',
      },
      {
        title: '전단지 배포 알바',
        location: '울산 남구 삼산동',
        pay: 116000,
        date: new Date('2025-07-24'),
        startTime: '12:00',
        endTime: '19:00',
        imageUrl: null,
        place: '홍대입구역 출구 앞',
        totalHours: 7,
        createdAt: new Date('2025-07-21T09:00:00'),
        content: '전단지 배포 알바 업무입니다.',
      },
      {
        title: '창고 정리 작업',
        location: '경기 성남시 분당구',
        pay: 118000,
        date: new Date('2025-07-26'),
        startTime: '07:00',
        endTime: '15:00',
        imageUrl: null,
        place: '물류창고 A동',
        totalHours: 8,
        createdAt: new Date('2025-07-20T19:00:00'),
        content: '창고 정리 작업 업무입니다.',
      },
      {
        title: '도서관 책 정리',
        location: '인천 연수구 송도동',
        pay: 123000,
        date: new Date('2025-09-08'),
        startTime: '10:00',
        endTime: '18:00',
        imageUrl: null,
        place: '중앙도서관',
        totalHours: 8,
        createdAt: new Date('2025-09-05T06:00:00'),
        content: '도서관 책 정리 업무입니다.',
      },
      {
        title: '커피숍 바리스타 보조',
        location: '서울 강남구 역삼동',
        pay: 91000,
        date: new Date('2025-09-18'),
        startTime: '12:00',
        endTime: '17:00',
        imageUrl: null,
        place: '스타벅스 선릉점',
        totalHours: 5,
        createdAt: new Date('2025-09-17T13:00:00'),
        content: '커피숍 바리스타 보조 업무입니다.',
      },
      {
        title: '아이스크림 매장 알바',
        location: '경기 성남시 분당구',
        pay: 26000,
        date: new Date('2025-09-04'),
        startTime: '10:00',
        endTime: '13:00',
        imageUrl: null,
        place: '배스킨라빈스 서울대점',
        totalHours: 3,
        createdAt: new Date('2025-08-31T18:00:00'),
        content: '아이스크림 매장 알바 업무입니다.',
      },
      {
        title: '핸드폰 매장 고객 응대',
        location: '울산 남구 삼산동',
        pay: 74000,
        date: new Date('2025-09-20'),
        startTime: '15:00',
        endTime: '19:00',
        imageUrl: null,
        place: 'KT강남지사',
        totalHours: 4,
        createdAt: new Date('2025-09-19T19:00:00'),
        content: '핸드폰 매장 고객 응대 업무입니다.',
      },
      {
        title: '패스트푸드 매장 카운터',
        location: '울산 남구 삼산동',
        pay: 73000,
        date: new Date('2025-09-01'),
        startTime: '11:00',
        endTime: '15:00',
        imageUrl: null,
        place: '맥도날드 서초점',
        totalHours: 4,
        createdAt: new Date('2025-08-26T05:00:00'),
        content: '패스트푸드 매장 카운터 업무입니다.',
      },
      {
        title: '주차 안내 요원',
        location: '대구 수성구 범어동',
        pay: 120000,
        date: new Date('2025-09-02'),
        startTime: '09:00',
        endTime: '15:00',
        imageUrl: null,
        place: '롯데백화점 강남점',
        totalHours: 6,
        createdAt: new Date('2025-08-27T20:00:00'),
        content: '주차 안내 요원 업무입니다.',
      },
      {
        title: '대형마트 행사 보조',
        location: '전북 전주시 완산구',
        pay: 93000,
        date: new Date('2025-09-04'),
        startTime: '14:00',
        endTime: '23:00',
        imageUrl: null,
        place: '이마트 트레이더스',
        totalHours: 9,
        createdAt: new Date('2025-08-31T16:00:00'),
        content: '대형마트 행사 보조 업무입니다.',
      },
      {
        title: '미용실 보조 스태프',
        location: '경남 창원시 의창구',
        pay: 38000,
        date: new Date('2025-09-14'),
        startTime: '16:00',
        endTime: '19:00',
        imageUrl: null,
        place: '헤어살롱 미지',
        totalHours: 3,
        createdAt: new Date('2025-09-12T05:00:00'),
        content: '미용실 보조 스태프 업무입니다.',
      },
      {
        title: 'PC방 카운터 및 청소',
        location: '경기 성남시 분당구',
        pay: 28000,
        date: new Date('2025-09-13'),
        startTime: '10:00',
        endTime: '13:00',
        imageUrl: null,
        place: 'XXPC방',
        totalHours: 3,
        createdAt: new Date('2025-09-09T10:00:00'),
        content: 'PC방 카운터 및 청소 업무입니다.',
      },
      {
        title: '분식집 포장 알바',
        location: '부산 해운대구 우동',
        pay: 72000,
        date: new Date('2025-09-17'),
        startTime: '06:00',
        endTime: '14:00',
        imageUrl: null,
        place: '신촌떡볶이',
        totalHours: 8,
        createdAt: new Date('2025-09-13T19:00:00'),
        content: '분식집 포장 알바 업무입니다.',
      },
      {
        title: '플리마켓 판매 보조',
        location: '부산 해운대구 우동',
        pay: 98000,
        date: new Date('2025-09-02'),
        startTime: '08:00',
        endTime: '17:00',
        imageUrl: null,
        place: '한강 플리마켓',
        totalHours: 9,
        createdAt: new Date('2025-08-29T00:00:00'),
        content: '플리마켓 판매 보조 업무입니다.',
      },
      {
        title: '의류매장 피팅 보조',
        location: '대전 서구 둔산동',
        pay: 137000,
        date: new Date('2025-09-19'),
        startTime: '13:00',
        endTime: '22:00',
        imageUrl: null,
        place: '유니클로 명동점',
        totalHours: 9,
        createdAt: new Date('2025-09-16T23:00:00'),
        content: '의류매장 피팅 보조 업무입니다.',
      },
      {
        title: '학원 청소 도우미',
        location: '울산 남구 삼산동',
        pay: 98000,
        date: new Date('2025-09-01'),
        startTime: '12:00',
        endTime: '17:00',
        imageUrl: null,
        place: 'OO영어학원',
        totalHours: 5,
        createdAt: new Date('2025-08-31T14:00:00'),
        content: '학원 청소 도우미 업무입니다.',
      },
      {
        title: '버스 정류장 안내',
        location: '전북 전주시 완산구',
        pay: 164000,
        date: new Date('2025-09-20'),
        startTime: '14:00',
        endTime: '24:00',
        imageUrl: null,
        place: '강남역 버스정류장',
        totalHours: 10,
        createdAt: new Date('2025-09-17T09:00:00'),
        content: '버스 정류장 안내 업무입니다.',
      },
      {
        title: '도시락 포장 알바',
        location: '경기 성남시 분당구',
        pay: 78000,
        date: new Date('2025-09-03'),
        startTime: '09:00',
        endTime: '16:00',
        imageUrl: null,
        place: '한솥도시락 마포점',
        totalHours: 7,
        createdAt: new Date('2025-08-31T06:00:00'),
        content: '도시락 포장 알바 업무입니다.',
      },
      {
        title: '호텔 청소 보조',
        location: '부산 해운대구 우동',
        pay: 99000,
        date: new Date('2025-09-17'),
        startTime: '07:00',
        endTime: '12:00',
        imageUrl: null,
        place: 'OO호텔',
        totalHours: 5,
        createdAt: new Date('2025-09-11T20:00:00'),
        content: '호텔 청소 보조 업무입니다.',
      },
      {
        title: '영화 촬영 보조 스태프',
        location: '광주 북구 중흥동',
        pay: 116000,
        date: new Date('2025-09-15'),
        startTime: '11:00',
        endTime: '17:00',
        imageUrl: null,
        place: '영화촬영장',
        totalHours: 6,
        createdAt: new Date('2025-09-09T12:00:00'),
        content: '영화 촬영 보조 스태프 업무입니다.',
      },
      {
        title: '야외 행사 지원 인력',
        location: '경남 창원시 의창구',
        pay: 62000,
        date: new Date('2025-09-12'),
        startTime: '08:00',
        endTime: '14:00',
        imageUrl: null,
        place: '도심광장 행사부스',
        totalHours: 6,
        createdAt: new Date('2025-09-07T18:00:00'),
        content: '야외 행사 지원 인력 업무입니다.',
      },
      {
        title: '반찬가게 포장 알바',
        location: '전북 전주시 완산구',
        pay: 123000,
        date: new Date('2025-09-18'),
        startTime: '09:00',
        endTime: '16:00',
        imageUrl: null,
        place: '엄마반찬',
        totalHours: 7,
        createdAt: new Date('2025-09-14T11:00:00'),
        content: '반찬가게 포장 알바 업무입니다.',
      },
      {
        title: '사진관 보조',
        location: '대전 서구 둔산동',
        pay: 48000,
        date: new Date('2025-09-17'),
        startTime: '18:00',
        endTime: '21:00',
        imageUrl: null,
        place: '사진관 하루',
        totalHours: 3,
        createdAt: new Date('2025-09-13T14:00:00'),
        content: '사진관 보조 업무입니다.',
      },
    ]);
  }
}
